static_resources:
  listeners:
    - name: "service-a-listener"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8786
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                tracing:
                  operation_name: ingress
                stat_prefix: "ingress_8786"
                codec_type: "AUTO"
                route_config:
                  name: servicea_route
                  virtual_hosts:
                    - name: service-a-svc-http-route
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service_a
                http_filters:
                  - name: envoy.router
    - name: "service-b-listener"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8788
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                tracing:
                  operation_name: egress
                stat_prefix: "egress_8788"
                codec_type: "AUTO"
                route_config:
                  name: service2_route
                  virtual_hosts:
                    - name: service2
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service_b
                http_filters:
                  - name: envoy.router

    - name: "service-c-listener"
      address:
        socket_address:
          address: 0.0.0.0
          port_value: 8790
      filter_chains:
        - filters:
            - name: envoy.http_connection_manager
              config:
                tracing:
                  operation_name: egress
                stat_prefix: "egress_8790"
                codec_type: "AUTO"
                route_config:
                  name: service2_route
                  virtual_hosts:
                    - name: service2
                      domains:
                        - "*"
                      routes:
                        - match:
                            prefix: "/"
                          route:
                            cluster: service_c
                http_filters:
                  - name: envoy.router
  clusters:
    - name: service_a
      connect_timeout: 0.250s
      type: strict_dns
      lb_policy: round_robin
      hosts:
        - socket_address:
            address: service_a
            port_value: 8081

    - name: service_b
      connect_timeout: 0.250s
      type: strict_dns
      lb_policy: round_robin
      hosts:
        - socket_address:
            address: service_b_envoy
            port_value: 8789

    - name: service_c
      connect_timeout: 0.250s
      type: strict_dns
      lb_policy: round_robin
      hosts:
        - socket_address:
            address: service_c_envoy
            port_value: 8791

    - name: jaeger
      connect_timeout: 1s
      type: strict_dns
      lb_policy: round_robin
      hosts:
        - socket_address:
            address: jaeger
            port_value: 9411

tracing:
  http:
    name: envoy.zipkin
    config:
      collector_cluster: jaeger
      collector_endpoint: "/api/v1/spans"
      shared_span_context: false
admin:
  access_log_path: "/tmp/admin_access.log"
  address:
    socket_address:
      address: 0.0.0.0
      port_value: 9901
